### ISSUE TITLE
Option to load pylintrc

### ISSUE THREAD

**Issue by zedrdave** [elarivie/atom-python-linters#4] opened 2020-05-16 08:50 UTC
As I [reported here](https://github.com/PyCQA/pylint/issues/3630), pylon's support for `setup.cfg` is still fledgling. Most options are not read altogether.

It would be great if you could add an option to read `pylintrc` when it is provided (or better yet, maybe: let `pylint` automatically pick according to its own logic). Especially since this plugin seems to be incompatible with the `linter-pylint` plugin (even with pylint set to `never` in the settings).

**Comment by elarivie** [comment] 2020-05-16 14:11
Hello @zedrdave,

What do you mean by:

> since this plugin seems to be incompatible with the linter-pylint plugin

Which incompatibility issue have you encountered?

**Comment by zedrdave** [comment] 2020-05-16 14:27
@elarivie Nevermind: I was getting some console noise about failing to delete some pylint-related files, but a few restart later and enabling only `mypy` in `python-linters` and `linter-pylint`, I no longer seem to have issues.

Given the lack of support for `setup.cfg` in `pylint`, an option would definitely be useful, though!

**Comment by elarivie** [comment] 2020-05-18 05:16
Closing...

1- Since the root cause of the issue is not in the atom package 'python-linters' but is instead in '[pylint](https://github.com/PyCQA/pylint/issues/3630)' 
2- Since there is a workaround which is to use the atom package 'linter-pylint'

**Closed by elarivie** 2020-05-18 05:16 UTC
Labels: question
